apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    # kubernetes.io/ingress.class: nginx # creating an Ingress controller base on Nginx project
    nginx.ingress.kubernetes.io/rewrite-target: / # rewrite the URL to remove '/api'
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: client-cluster-ip-service
                port: 
                  number: 3000
          - path: /api/
            pathType: Prefix
            backend:
              service: 
                name: server-cluster-ip-service
                port: 
                  number: 5000